---
title: "Homework 3"
author: "Your Name Here"
date: "2023-09-28"
output: html_document
editor_options: 
  chunk_output_type: console
---
Submit this rmd file on Sakia as a knitted document. Don't forget to add your own code chunks.

1. Use the `Batting`, `Pitching`, and `People` tables in the Lahman package to answer the following questions:

a) (20 points) Name every player in baseball history who has accumulated at least 300 home runs (HR) AND at least 300 stolen bases (SB). You can find the first and last name of the player in the `People` data frame. Join this to your result along with the total home runs and total bases stolen for each of these elite players.

b) (20 points) Similarly, name every pitcher in baseball history who has accumulated at least 300 wins (W) and at least 3,000 strikeouts (SO). 

c) (20 points) Identify the name and year of every player who has hit at least 50 home runs in a single season. Which player had the lowest batting average in that season?


2. Use the nycflights13 package and the `flights` and `planes` tables to answer the following questions:

a) (20 points) What is the oldest plane (specified by the tailnum variable) that flew from New York City airports in 2013?

b) (20 points) How many airplanes that flew from New York City are included in the planes table?